### PR TITLE
fix: shim-fs break when process.nexe is undefined

### PR DESCRIPTION
**Pull request by jaredallard**
I'm sure this leads to a bigger issue that `process.nexe` is undefined in the first place... which is why this is on a separate branch. Will investigate it further in the morning.

Please squash and merge this if merging

### CODE REVIEW

**Comment by calebboyd** [comment]
I can clarify that -- 

the `no-bundle` branch requires new pre-built binaries. Which are stored in github releases. and its not ready to go yet so no new ones are up.

To dev on it locally use `--build` (slow once). The new builds will be backwards compatible with the old client, but old builds won't be forwards compatible so we can use this error know when to display a helpful error message. (eg. use `--clean` once)

I was also having a million and one problems with yarn on my windows box... So i switched back to npm... which is actually pretty pleasant 5.6+

**Comment by jaredallard** [comment]
Windows 😲 No yarn? 😲😲😲Bold moves for 2018..... Hahah. Yeah I noticed it's not working at all right now (nor does `dev` for the program @ work I'm trying to 'encapsulate', so I'm forced to contribute now!). 

Trying to figure it all out and see what's not implemented and why. I figured it was something with the binaries. I'll add logic for the error display instead of ""working around"" the problem.

**Comment by calebboyd** [comment]
What'd you run into in dev? Something i imagine with issue 418...?

**Comment by jaredallard** [comment]
Basically I'm trying to bundle a `commander.js` application and it just doesn't work. It executes stuff but doesn't... There's no real way for me to debug it either so I was hoping this more 'native' way would work.

Also was your issue with yarn that you couldn't, like, `yarn link resolve-dependencies`? Ran into that hacking on resolve-dep*

**Comment by calebboyd** [comment]
Yep, any sort of linking was a nightmare, and and a few other one off windows bugs that have been open forever :(

**Pull request closed without merging**
