### PR TITLE
Fixed windows path bug

### PR DESCRIPTION
**Pull request by IshaiJaffe**
Before this change I had problems running the exe file created on windows. The fix is very simple.

### CODE REVIEW

**Comment by calebboyd** [comment]
Can you provide the configuration that you used with nexe?

The change you've made does not work well (potentially) for non-windows binaries.

**Comment by IshaiJaffe** [comment]
Hi,
I have a simply nodejs app that preprocess and serve static files. The app
should work on Linux and Windows, and the packaging process could be done
in Linux or in Windows.
So I'm using nexe (which is great) to generate executables. In my package
Json I have scripts that run nexe.

I'm running from both windows and linux:
nexe main.js --target <linux-64-node-version>
nexe main.js --target <win-64-node-version>

Before the fix, the executable generated in Windows, failed on execution.
The exception was about bad syntax in string. I saw that the string
contains \ characters which should be escaped. This is because the shim.ts
adds the path to a string without escaping this \ character, which is
always used in windows.

I have tested this fix in windows and in linux. Also I don't think it
should break anything. The \ character should always be escaped when you
doing eval from a string variable, in both Linux and Windows. FYI, there
are other special characters that should be escaped like quotation marks.
This fix is very specific. A more robust solution will be to use the
escaping of JSON.stringify to do just that.

ᐧ

All the best,

*Ishai Jaffe*
CTO

<https://www.bablic.com/>

*M:* +972-50-8455243
*W: *www.bablic.com

<https://www.facebook.com/babliclocalization>
<https://twitter.com/bablic_com>   <https://www.linkedin.com/company/bablic>


.......................................................................................................................

CONFIDENTIALITY NOTICE This email is ONLY for the person(s) named in the
message header.Unless otherwise indicated, it contains information that is
confidential, privileged or exempt from disclosure under applicable law. If
you have received it in error, please notify the sender of the error and
delete the message. Thank you.

**Comment by calebboyd** [comment]
Can you provide steps to reproduce? I'm having trouble finding when this would occur, because `input` is already normalized prior to this code being run.

**Comment by IshaiJaffe** [comment]
input is normalized. But when you paste a string that will later be
evaluated as Javascript you need to escape some characters.

Probably you couldnt reproduce because you didnt really paid attention to
the script name argument.
But if the path includes a folder of file that starts with lower case 'x'
following a character that is not a-f you will get "unrexognized hex string"
How to reproduce:
create a script in windows folder named xs.js:
c:\Users\User\xs.js
The script will do console.log('OK');

run in windows cmd

nexe xs.js --outout dist/xs
cd dist
xs.exe

בתאריך 14 בנוב׳ 2017 4:04 אחה״צ,‏ "calebboyd" <notifications@github.com>
כתב:

Can you provide steps to reproduce? I'm having trouble finding when this
would occur, because input is already normalized prior to this code being
run.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nexe/nexe/pull/422#issuecomment-344268434>, or mute the
thread

**Comment by calebboyd** [comment]
Thanks! I've changed the serialization to use stringify, I also adjusted the git user to a valid git user (yours). 

23f550818bba51253f3120a5301d3c27e67de5f3
nexe@2.0.0-rc.20

**Pull request closed without merging**
