### PR TITLE
Include snapshot in patches

### PR DESCRIPTION
**Pull request by anmonteiro**
Looks like this might have been forgotten.

### CODE REVIEW

**Comment by calebboyd** [comment]
Is this the patch you were referring to in #538 ?

**Comment by anmonteiro** [comment]
It's kinda related. Once you wanna support Node.js v10.11 + you need to switch on the Node.js version in `lib/patches/snapshot` to patch either `configure` or `configure.py`.

This PR allows snapshots which were out of the default patches.

**Comment by anmonteiro** [comment]
I think we might also have to change the snapshot path to include the absolute path to the snapshot file. I'm trying it out with the relative path right now.

**Comment by anmonteiro** [comment]
@calebboyd Yep, looks like we need absolute paths. Updated the PR accordingly.

**Pull request merged**
