### PR TITLE
fix utf-8 issue

### PR DESCRIPTION
**Pull request by koprda**
#206
#224

### CODE REVIEW

**Comment by JamesMGreene** [comment]
@jaredallard @calebboyd Is this still relevant for building with Node < 7?

**Comment by calebboyd** [comment]
if you'd like to include this please re-open against V1-EOL

**Comment by thbl** [comment]
@calebboyd  when i compile my app dosen't work and i get some utf8 error.
but if i remove the "source = source.replace(/[^\x00-\x7F]/g, "");"
and compile my app works fine. 

Maby a stupid question... But what does the code do ? and is there any harm to remove it ?

**Comment by JamesMGreene** [comment]
It removes all characters that are **NOT** within the "Basic Latin" (US-ASCII) character block (all of the 1-byte characters, of which there are 128).

This therefore, unfortunately, excludes a ton of valid Unicode code points (all of the 2-4 byte characters, of which there are 1,111,936).

I'm not sure what the intent was with this code being added in the first place but it seems pretty flawed to me at a [blissfully ignorant] first glance.

**Comment by JamesMGreene** [comment]
Here's the original commit that added it but, unfortunately, its commit message doesn't add much context:
https://github.com/nexe/nexe/commit/b803ae7dddd5f0ae7e1b279310ff5505c6507482

**Comment by calebboyd** [comment]
Not sure either, here is the original original :)
https://github.com/nexe/nexe/commit/552158485cf31dddd8b215e7bd015d922d40576b

**Comment by JamesMGreene** [comment]
Original issue: #63
Original PR: #79 

Though even with that info, I don't see how remove all non-ASCII characters would solve the problem of the bundler choking on Unicode... wouldn't you just end up with a bunch of files that have lost their integrity?

**Pull request closed without merging**
