### PR TITLE
Corrected chain-loading path in index.js

### PR DESCRIPTION
**Pull request by JamesMGreene**
Otherwise I get:

```
module.js:327
    throw err;
    ^

Error: Cannot find module './lib/nexe'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\git\Observer\Node\ObsNode\node_modules\nexe\index.js:2:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

### CODE REVIEW

**Comment by JamesMGreene** [comment]
Hmm, looks like there is more to this one.

**Comment by calebboyd** [comment]
`npm run build`

**Comment by JamesMGreene** [comment]
Ah, I see.

**Comment by calebboyd** [comment]
Is there a particular reason you want to include the src in the npm package?

**Comment by JamesMGreene** [comment]
No, I guess I was just confused.  I installed the current code like `npm install nexe/nexe#master`, so NPM did not pull down the full repo given that there is a `files` inclusion only for `"lib"` in the package.json file.

**Comment by calebboyd** [comment]
If you're running locally, I'd suggest using `npm link` + `npm run build` after a change

**Comment by JamesMGreene** [comment]
> As an update. I should have 'bindings' support this weekend

Interested to see how that looks! :+1:

**Pull request closed without merging**
